### ISSUE TITLE
How to access Gatt.Close using plugin 

### ISSUE THREAD

**Issue by AnoopChatra** [xabre/xamarin-bluetooth-le#137]
I am trying to connect to a BLE device using  adapter.ConnectToDeviceAsync(deviceToBeConnected).  Most of the time i am  ending up with GATT 133 error.
The solutions suggests to call "close" on a GATT object after we call adapter.disconnect(). However i am unable to access the Gatt object.

Is there any other solution to solve GATT 133 error in android ?? It usually occurs while connecting to BLE.

### Crashlog
BluetoothLeException: DeviceConnectionException occured in Connect()  ---> Plugin.BLE.Abstractions.Exceptions.DeviceConnectionException: GattCallback error: 133

## Configuration

**Version of the Plugin:** Plugin.BLE.1.2.0-beta3

**Platform:**  Android 6.0 / 

**Device:** Samsung s7

**Comment by xabre** [comment]
We already call gatt.Close() once we get the disconnect callback. You can check it in GattCallback.cs inside our Android implementation.  It's difficult to say why you get this error that often. The gatt object will never be available directly in our cross platform BLE abstraction because it's a very specific android class. 
What you can do is clone the repo, reference the required BLE csporjects in your solution and try to debug it, w ould be very helpful if you find an improvement.
