### ISSUE TITLE
Question: Plugin BLE for Android

### ISSUE THREAD

**Issue by alberk8** [xabre/xamarin-bluetooth-le#44]
I am interested in your Plugin BLE for Android.   I would really help me to understand if there is sample app.  Thank you.

**Comment by xabre** [comment]
@alberk8 Yes you can find the sample app in the solution (subfolder). [Client](https://github.com/xabre/xamarin-bluetooth-le/tree/master/Source/BLE.Client)

**Comment by alberk8** [comment]
Hi,

The sample is based on the MvvmCross.  What I need is just plain vanilla Android sample.  Thank you.

**Comment by xabre** [comment]
It works the same. The only difference is that instead of resolving the IBluetoothLE interface using MvvmCross dependecy injection you do it statically by using **CrossBluetoothLE.Current**. Everything else works the same.

**Comment by alberk8** [comment]
Sorry for bothering.  I am a newbie in c# and Xamarin so a sample app on Android would be very helpful.   Thank you again.

**Comment by smstuebe** [comment]
The sample app is for Android and iOS. We won't provide a pure Android example (without Xamarin.Forms) project because this is too much effort for maintenance. The plugin works independent from the used UI technology. 

Take some time and analyze the sample well. But keep in mind that `IAdapter` isn't 'magically' injected by MvvmCross and you have to use `CrossBluetoothLE.Current.Adapter` to get it. If you have concrete questions, just ask them.
