### ISSUE TITLE
Why location permission is mandatory?

### ISSUE THREAD

**Issue by rajnikantpatel23** [xabre/xamarin-bluetooth-le#581]
Hi, Can someone please explain why Location permission is mandatory for this nuget to work. Does it improve accuracy for pairing? Does it make pairing faster? Or some other benefit?

**Comment by smsissuechecker** [comment]
Hi @rajnikantpatel23,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
> Hi, Can someone please explain why Location permission is mandatory for this nuget to work. Does it improve accuracy for pairing? Does it make pairing faster? Or some other benefit?

Well, this requirement is not specific to this project. It is dictated by the Android OS. Also it has nothing to do with improving or speeding up the pairing process. AFAIK it was introduced in Android, because one can in principle use Bluetooth data to deduce location. And in fact the requirement has been lifted in Android 12, with which it is possible now to use Bluetooth without the location permission.

**Comment by janusw** [comment]
See also #568.
